//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaoMatCSDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOP
    {
        public LOP()
        {
            this.SINHVIENs = new HashSet<SINHVIEN>();
        }
    
        public string MALOP { get; set; }
        public string TENLOP { get; set; }
        public string MANV { get; set; }
    
        public virtual NHANVIEN NHANVIEN { get; set; }
        public virtual ICollection<SINHVIEN> SINHVIENs { get; set; }
    }
}
