//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaoMatCSDL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QLSVEntities : DbContext
    {
        public QLSVEntities()
            : base("name=QLSVEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LOP> LOPs { get; set; }
        public virtual DbSet<NHANVIEN> NHANVIENs { get; set; }
        public virtual DbSet<SINHVIEN> SINHVIENs { get; set; }
    
        public virtual int SP_INS_ENCRYPT_NHANVIEN(string mANV, string hOTEN, string eMAIL, byte[] e_LUONG, string tENDN, byte[] e_MATKHAU)
        {
            var mANVParameter = mANV != null ?
                new ObjectParameter("MANV", mANV) :
                new ObjectParameter("MANV", typeof(string));
    
            var hOTENParameter = hOTEN != null ?
                new ObjectParameter("HOTEN", hOTEN) :
                new ObjectParameter("HOTEN", typeof(string));
    
            var eMAILParameter = eMAIL != null ?
                new ObjectParameter("EMAIL", eMAIL) :
                new ObjectParameter("EMAIL", typeof(string));
    
            var e_LUONGParameter = e_LUONG != null ?
                new ObjectParameter("E_LUONG", e_LUONG) :
                new ObjectParameter("E_LUONG", typeof(byte[]));
    
            var tENDNParameter = tENDN != null ?
                new ObjectParameter("TENDN", tENDN) :
                new ObjectParameter("TENDN", typeof(string));
    
            var e_MATKHAUParameter = e_MATKHAU != null ?
                new ObjectParameter("E_MATKHAU", e_MATKHAU) :
                new ObjectParameter("E_MATKHAU", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_INS_ENCRYPT_NHANVIEN", mANVParameter, hOTENParameter, eMAILParameter, e_LUONGParameter, tENDNParameter, e_MATKHAUParameter);
        }
    
        public virtual int SP_INS_ENCRYPT_SINHVIEN(string mASV, string hOTEN, Nullable<System.DateTime> nGAYSINH, string dIACHI, string mALOP, string tENDN, byte[] mATKHAU)
        {
            var mASVParameter = mASV != null ?
                new ObjectParameter("MASV", mASV) :
                new ObjectParameter("MASV", typeof(string));
    
            var hOTENParameter = hOTEN != null ?
                new ObjectParameter("HOTEN", hOTEN) :
                new ObjectParameter("HOTEN", typeof(string));
    
            var nGAYSINHParameter = nGAYSINH.HasValue ?
                new ObjectParameter("NGAYSINH", nGAYSINH) :
                new ObjectParameter("NGAYSINH", typeof(System.DateTime));
    
            var dIACHIParameter = dIACHI != null ?
                new ObjectParameter("DIACHI", dIACHI) :
                new ObjectParameter("DIACHI", typeof(string));
    
            var mALOPParameter = mALOP != null ?
                new ObjectParameter("MALOP", mALOP) :
                new ObjectParameter("MALOP", typeof(string));
    
            var tENDNParameter = tENDN != null ?
                new ObjectParameter("TENDN", tENDN) :
                new ObjectParameter("TENDN", typeof(string));
    
            var mATKHAUParameter = mATKHAU != null ?
                new ObjectParameter("MATKHAU", mATKHAU) :
                new ObjectParameter("MATKHAU", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_INS_ENCRYPT_SINHVIEN", mASVParameter, hOTENParameter, nGAYSINHParameter, dIACHIParameter, mALOPParameter, tENDNParameter, mATKHAUParameter);
        }
    
        public virtual int SP_INS_NHANVIEN(string mANV, string hOTEN, string eMAIL, string lUONG, string tENDN, string mATKHAU)
        {
            var mANVParameter = mANV != null ?
                new ObjectParameter("MANV", mANV) :
                new ObjectParameter("MANV", typeof(string));
    
            var hOTENParameter = hOTEN != null ?
                new ObjectParameter("HOTEN", hOTEN) :
                new ObjectParameter("HOTEN", typeof(string));
    
            var eMAILParameter = eMAIL != null ?
                new ObjectParameter("EMAIL", eMAIL) :
                new ObjectParameter("EMAIL", typeof(string));
    
            var lUONGParameter = lUONG != null ?
                new ObjectParameter("LUONG", lUONG) :
                new ObjectParameter("LUONG", typeof(string));
    
            var tENDNParameter = tENDN != null ?
                new ObjectParameter("TENDN", tENDN) :
                new ObjectParameter("TENDN", typeof(string));
    
            var mATKHAUParameter = mATKHAU != null ?
                new ObjectParameter("MATKHAU", mATKHAU) :
                new ObjectParameter("MATKHAU", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_INS_NHANVIEN", mANVParameter, hOTENParameter, eMAILParameter, lUONGParameter, tENDNParameter, mATKHAUParameter);
        }
    
        public virtual int SP_INS_SINHVIEN(string mASV, string hOTEN, Nullable<System.DateTime> nGAYSINH, string dIACHI, string mALOP, string tENDN, string mATKHAU)
        {
            var mASVParameter = mASV != null ?
                new ObjectParameter("MASV", mASV) :
                new ObjectParameter("MASV", typeof(string));
    
            var hOTENParameter = hOTEN != null ?
                new ObjectParameter("HOTEN", hOTEN) :
                new ObjectParameter("HOTEN", typeof(string));
    
            var nGAYSINHParameter = nGAYSINH.HasValue ?
                new ObjectParameter("NGAYSINH", nGAYSINH) :
                new ObjectParameter("NGAYSINH", typeof(System.DateTime));
    
            var dIACHIParameter = dIACHI != null ?
                new ObjectParameter("DIACHI", dIACHI) :
                new ObjectParameter("DIACHI", typeof(string));
    
            var mALOPParameter = mALOP != null ?
                new ObjectParameter("MALOP", mALOP) :
                new ObjectParameter("MALOP", typeof(string));
    
            var tENDNParameter = tENDN != null ?
                new ObjectParameter("TENDN", tENDN) :
                new ObjectParameter("TENDN", typeof(string));
    
            var mATKHAUParameter = mATKHAU != null ?
                new ObjectParameter("MATKHAU", mATKHAU) :
                new ObjectParameter("MATKHAU", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_INS_SINHVIEN", mASVParameter, hOTENParameter, nGAYSINHParameter, dIACHIParameter, mALOPParameter, tENDNParameter, mATKHAUParameter);
        }
    
        public virtual ObjectResult<SP_SEL_NHANVIEN_Result> SP_SEL_NHANVIEN()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SEL_NHANVIEN_Result>("SP_SEL_NHANVIEN");
        }
    }
}
