//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaoMatCSDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SINHVIEN
    {
        public string MASV { get; set; }
        public string HOTEN { get; set; }
        public Nullable<System.DateTime> NGAYSINH { get; set; }
        public string DIACHI { get; set; }
        public string MALOP { get; set; }
        public string TENDN { get; set; }
        public byte[] MATKHAU { get; set; }
    
        public virtual LOP LOP { get; set; }
    }
}
