/*---------------------------------------------------------- 
MASV: 1112072
HO TEN: Trần Hải Đăng
LAB: 03 
NGAY:  20/5/2014
----------------------------------------------------------*/ 

USE MASTER
IF DB_ID ('QLSV') IS NOT NULL
	DROP DATABASE QLSV
GO
CREATE DATABASE QLSV
GO
USE QLSV
GO

CREATE TABLE SINHVIEN
(
	MASV NVARCHAR(20),
	HOTEN NVARCHAR(100),
	NGAYSINH DATETIME,  
	DIACHI NVARCHAR(200),  
	MALOP VARCHAR (20),  
	TENDN NVARCHAR(100),
	MATKHAU VARBINARY(128),
	PRIMARY KEY(MASV)
)

CREATE TABLE NHANVIEN
(
	MANV VARCHAR (20),
	HOTEN NVARCHAR(100),
	EMAIL VARCHAR (20),  
	LUONG VARBINARY(256),  
	TENDN NVARCHAR(100),
	MATKHAU VARBINARY(256),
	PRIMARY KEY(MANV)
)

CREATE TABLE LOP
(
	MALOP VARCHAR (20),
	TENLOP NVARCHAR(100),
	MANV VARCHAR (20),
	PRIMARY KEY (MALOP)  
)


ALTER TABLE SINHVIEN
	ADD CONSTRAINT FK_SINHVIEN_LOP
	FOREIGN KEY (MALOP) REFERENCES LOP(MALOP)

ALTER TABLE LOP
	ADD CONSTRAINT FK_LOP_NHANVIEN
	FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)



CREATE MASTER KEY ENCRYPTION BY PASSWORD = '1112392';
GO
CREATE CERTIFICATE [cert_keyProtection] WITH SUBJECT = 'QLSV';
GO
CREATE SYMMETRIC KEY [AES256MYKEY] WITH
    KEY_SOURCE = 'My key generation bits. This is a shared secret!',
    ALGORITHM = AES_256, 
    IDENTITY_VALUE = 'Key Identity generation bits. Also a shared secret'
    ENCRYPTION BY CERTIFICATE [cert_keyProtection];
GO


